/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert2: typeof import('./components/alert2.vue')['default']
    AlertNotification: typeof import('./components/AlertNotification.vue')['default']
    AppFooter: typeof import('./components/vue-default/AppFooter.vue')['default']
    FoodCard: typeof import('./components/FoodCard.vue')['default']
    Health: typeof import('./components/health.vue')['default']
    Health2: typeof import('./components/health2.vue')['default']
    Health3: typeof import('./components/health.vue')['default']
    HealthSummaryCard: typeof import('./components/HealthSummaryCard.vue')['default']
    Meals: typeof import('./components/meals.vue')['default']
    Meals2: typeof import('./components/meals2.vue')['default']
    Meals3: typeof import('./components/meals3.vue')['default']
    Meals4: typeof import('./components/meals.vue')['default']
    MealsSummaryCard: typeof import('./components/MealsSummaryCard.vue')['default']
    MoodCard: typeof import('./components/MoodCard.vue')['default']
    Poop: typeof import('./components/poop.vue')['default']
    Poop2: typeof import('./components/poop2.vue')['default']
    Poop3: typeof import('./components/poop.vue')['default']
    Poop4: typeof import('./components/poop4.vue')['default']
    PoopSummaryCard: typeof import('./components/PoopSummaryCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sleep: typeof import('./components/sleep.vue')['default']
    Sleep2: typeof import('./components/sleep2.vue')['default']
    Sleep3: typeof import('./components/sleep3.vue')['default']
    Sleep4: typeof import('./components/sleep4.vue')['default']
    SleepCard: typeof import('./components/SleepCard.vue')['default']
    SleepSummaryCard: typeof import('./components/SleepSummaryCard.vue')['default']
  }
}
