/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddChildForm: typeof import('./components/addChild/AddChildForm.vue')['default']
    AIAssistant: typeof import('./components/chatbot/AIAssistant.vue')['default']
    AlertCard: typeof import('./components/guidance/AlertCard.vue')['default']
    AlertsView: typeof import('./components/guidance/AlertsView.vue')['default']
    AppFooter: typeof import('./components/vue-default/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppNavigation: typeof import('./components/AppNavigation.vue')['default']
    ArticleCard: typeof import('./components/guidance/ArticleCard.vue')['default']
    ArticleGrid: typeof import('./components/guidance/ArticleGrid.vue')['default']
    BaseCheckInDialog: typeof import('./components/dialog/BaseCheckInDialog.vue')['default']
    BaseDialog: typeof import('./components/dialog/BaseDialog.vue')['default']
    BaseSummaryCard: typeof import('./components/summaryCard/BaseSummaryCard.vue')['default']
    ChatContent: typeof import('./components/chatbot/ChatContent.vue')['default']
    ChatSidebar: typeof import('./components/chatbot/ChatSidebar.vue')['default']
    CheckInsHistory: typeof import('./components/CheckInsHistory.vue')['default']
    ChildNameInput: typeof import('./components/addChild/ChildNameInput.vue')['default']
    DateOfBirthPicker: typeof import('./components/addChild/DateOfBirthPicker.vue')['default']
    GenderSelect: typeof import('./components/addChild/GenderSelect.vue')['default']
    GrowthDialog: typeof import('./components/dialog/GrowthDialog.vue')['default']
    HealthAlert: typeof import('./components/HealthAlert.vue')['default']
    HealthSummaryCard: typeof import('./components/summaryCard/HealthSummaryCard.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    LogMealDialog: typeof import('./components/dialog/LogMealDialog.vue')['default']
    MealDialog: typeof import('./components/dialog/MealDialog.vue')['default']
    MealsSummaryCard: typeof import('./components/summaryCard/MealsSummaryCard.vue')['default']
    NavigationTabs: typeof import('./components/guidance/NavigationTabs.vue')['default']
    PoopDialog: typeof import('./components/dialog/PoopDialog.vue')['default']
    PoopSummaryCard: typeof import('./components/summaryCard/PoopSummaryCard.vue')['default']
    ProfilePhotoUpload: typeof import('./components/addChild/ProfilePhotoUpload.vue')['default']
    RelationshipSelect: typeof import('./components/addChild/RelationshipSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedView: typeof import('./components/guidance/SavedView.vue')['default']
    SleepDialog: typeof import('./components/dialog/SleepDialog.vue')['default']
    SleepSummaryCard: typeof import('./components/summaryCard/SleepSummaryCard.vue')['default']
    SubmitButton: typeof import('./components/addChild/SubmitButton.vue')['default']
    SymptomDialog: typeof import('./components/dialog/SymptomDialog.vue')['default']
    SymptompsDialog: typeof import('./components/dialog/SymptompsDialog.vue')['default']
    TodaysSummary: typeof import('./components/summaryCard/TodaysSummary.vue')['default']
    WelcomeSection: typeof import('./components/login/WelcomeSection.vue')['default']
  }
}
