/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/index.bak': RouteRecordInfo<'/index.bak', '/index/bak', Record<never, never>, Record<never, never>>,
    '/index2': RouteRecordInfo<'/index2', '/index2', Record<never, never>, Record<never, never>>,
    '/index3': RouteRecordInfo<'/index3', '/index3', Record<never, never>, Record<never, never>>,
    '/indextest': RouteRecordInfo<'/indextest', '/indextest', Record<never, never>, Record<never, never>>,
    '/poopdialog': RouteRecordInfo<'/poopdialog', '/poopdialog', Record<never, never>, Record<never, never>>,
  }
}
